version: '2.2'

services:
  cubejs:
    image: cubejs/cube:v0.33.38
    ports:
      - 4000:4000
      - 3000:3000
      - 5432:5432
    volumes:
      - ./cube:/cube/conf
    environment:
      - DATASET_ID=xxx
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_DB_BQ_PROJECT_ID=xxx
      - CUBEJS_DB_BQ_KEY_FILE=/cube/conf/bigquerycreds.json
      - CUBEJS_DB_EXPORT_BUCKET=cubestore_test
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_PG_SQL_PORT=5432
      - CUBEJS_SQL_USER=myusername
      - CUBEJS_SQL_PASSWORD=mypassword
      - CUBEJS_API_SECRET=secret
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
      - cubestore_worker_2

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:v0.33.38
    environment:
      - DATASET_ID=agoric_localchain_0
      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_DB_BQ_PROJECT_ID=xxx
      - CUBEJS_DB_BQ_CREDENTIALS=/bigquerycreds.json
      - CUBEJS_DB_EXPORT_BUCKET=cubestore_test
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_API_SECRET=secret
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - ./cube:/cube/conf

  cubestore_router:
    restart: always
    image: cubejs/cubestore:v0.33.38
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:v0.33.38
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:v0.33.38
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router
