version: '2.2'

services:
  dashboard:
    build:
      context: ./dashboard
    ports:
      - 8080:80

  txdecode:
    build:
      context: .
    environment:
      PORT: "8081"
    command:
      - "http-processor"
      - "agd"
      - "txdecode"

  head-indexer: &indexer
    restart: always
    stop_grace_period: 600s
    depends_on:
      - "txdecode"
    build:
      context: .
    environment:
      TENDERMINT_TRIGGER_RPC_URL: "${TENDERMINT_RPC_URL}"
      TENDERMINT_TRIGGER_PROJECT_ID: "${PROJECT_ID}"
      TENDERMINT_TRIGGER_DATASET_ID: "${DATASET_ID}"
      TENDERMINT_TRIGGER_BATCH_SIZE: 10
      TENDERMINT_TRIGGER_MAX_WRITE_COUNT: 100
      TENDERMINT_TRIGGER_BASE_CONFIG: '{"rpc_url":"${TENDERMINT_TRIGGER_RPC_URL}","batch_size":32,"thread_count":24}'
      GOOGLE_APPLICATION_CREDENTIALS: "/bigquerycreds.json"
      DECODE_SERVICE_URL: "http://txdecode:8080"
    volumes:
      - "${GOOGLE_CREDS}:/bigquerycreds.json"
      - "/tmp:/tmp"
    entrypoint:
      - "tendermint-trigger"
      - "head"
      - "./extract-tendermint.sh"

  cubejs:
    image: cubejs/cube:v0.33.38
    ports:
      - 4000:4000
      - 3000:3000
      - 5432:5432
    environment:
      - DATASET_ID=${DATASET_ID}
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_DB_BQ_PROJECT_ID=${PROJECT_ID}
      - CUBEJS_DB_BQ_KEY_FILE=/bigquerycreds.json
      - CUBEJS_DB_EXPORT_BUCKET=${EXPORT_BUCKET}
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_PG_SQL_PORT=5432
      - CUBEJS_SQL_USER=myusername
      - CUBEJS_SQL_PASSWORD=mypassword
      - CUBEJS_API_SECRET=secret
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
      - cubestore_worker_2
    volumes:
      - ./cube:/cube/conf
      - "${GOOGLE_CREDS}:/bigquerycreds.json"

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:v0.33.38
    environment:
      - DATASET_ID=${DATASET_ID}
      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_DB_BQ_PROJECT_ID=${PROJECT_ID}
      - CUBEJS_DB_BQ_CREDENTIALS=/bigquerycreds.json
      - CUBEJS_DB_EXPORT_BUCKET=${EXPORT_BUCKET}
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_API_SECRET=secret
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - ./cube:/cube/conf
      - "${GOOGLE_CREDS}:/bigquerycreds.json"

  cubestore_router:
    restart: always
    image: cubejs/cubestore:v0.33.38
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:v0.33.38
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:v0.33.38
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router
