---
apiVersion: v1
kind: Service
metadata:
  name: cube-mainnet-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: cube-mainnet
    app.kubernetes.io/name: cube
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: cube-ollinet-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: cube-ollinet
    app.kubernetes.io/name: cube
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: cube-emerynet-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: cube-emerynet
    app.kubernetes.io/name: cube
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: cube-devnet-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: cube-devnet
    app.kubernetes.io/name: cube
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cube-gke
  annotations:
    kubernetes.io/ingress.global-static-ip-name: agoric-dashboard
spec:
  defaultBackend:
    service:
      name: dashboard-nodeport
      port:
        name: http
  rules:
    - http:
        paths:
          - path: /cubejs-api/agoric_mainnet/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cube-mainnet-nodeport
                port:
                  name: http

          - path: /cubejs-api/agoric_emerynet/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cube-emerynet-nodeport
                port:
                  name: http

          - path: /cubejs-api/agoric_ollinet/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cube-ollinet-nodeport
                port:
                  name: http

          - path: /cubejs-api/agoric_devnet/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cube-devnet-nodeport
                port:
                  name: http
