---
apiVersion: v1
kind: Service
metadata:
  name: cube-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: cube
    app.kubernetes.io/name: cube
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cube-gke
  annotations:
    kubernetes.io/ingress.global-static-ip-name: agoric-dashboard
spec:
  rules:
    - http:
        paths:
          - path: /cubejs-api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cube-nodeport
                port:
                  name: http
