# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: your-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rpcUrl: "" # https://main.rpc.agoric.net"
grpcAddr: ""

googleCredsSecretName: "indexer-google-creds"
projectId: "your-project-id"
datasetId: "your-dataset-id"
extractBlockBatchSize: 200
decodeServiceUrl: "cloud run url"

tendermintHead:
  enabled: true

tendermintTail:
  enabled: true

balances:
  enabled: false
  shedule: "*/10 * * * *"
  addresses: ""

coingeko:
  enabled: false
  shedule: "0 * * * *"

sloMetrics:
  enabled: true
  shedule: "30 * * * *"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 2000
  runAsUser: 2000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

tailIndexerResources:
  limits:
    cpu: 3250m
    memory: 3.25Gi
  requests:
    cpu: 3250m
    memory: 3.25Gi

headIndexerResources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi

cronjobResources:
  limits:
    cpu: 0.5
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
