name: Build and publish Docker image

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  publish:
    name: Build and push Docker image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta for the main image
        id: main_meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            europe-west4-docker.pkg.dev/tooling-team-371411/general/agoric-extractor
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta for the dashboard image
        id: dashboard_meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            europe-west4-docker.pkg.dev/tooling-team-371411/general/agoric-dashboard
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta for the cubejs image
        id: cubejs_meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            europe-west4-docker.pkg.dev/tooling-team-371411/general/agoric-cube
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta for the oldapi image
        id: oldapi_meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            europe-west4-docker.pkg.dev/tooling-team-371411/general/agoric-oldapi
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: europe-west4-docker.pkg.dev
          username: _json_key
          password: "${{ secrets.GAR_JSON_KEY }}"

      - name: Build and push the main image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.main_meta.outputs.tags }}

      - name: Build and push the dashboard image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./dashboard
          tags: ${{ steps.dashboard_meta.outputs.tags }}

      - name: Build and push the cube image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./cube
          tags: ${{ steps.cubejs_meta.outputs.tags }}

      - name: Build and push the oldapi image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./oldapi
          tags: ${{ steps.oldapi_meta.outputs.tags }}
