name: Lint, Test, and Type Check tendermint-normalizer

on:
  push:
    paths:
      - "tendermint-normalizer/**"
      - ".github/workflows/check-tendermint-normalizer.yml"

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tendermint-normalizer

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"


      - name: Install flake8
        run: pip install flake8

      - name: Lint with flake8
        run: flake8 --count --statistics

  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tendermint-normalizer

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"


      - name: Run Python Tests
        run: python -m unittest discover

  type_check:
    name: Type Check with mypy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tendermint-normalizer

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"


      - name: Install mypy
        run: pip install mypy  types-ujson types-requests types-python-dateutil

      - name: Type Check with mypy
        run: mypy .
 
