name: Lint and Test BqReader

on:
  push:
    paths:
      - "bqreader/**"
      - ".github/workflows/check-bqreader.yaml"

jobs:
  lint:
    name: Lint with GoLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bqreader

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install GoLint
        run: go install golang.org/x/lint/golint@latest

      - name: Lint with GoLint
        run: golint ./...

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bqreader

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Go Tests
        run: go test ./...

 
