name: Build and Push Docker image

on:
  push:
    branches:
      - ci/deployments

env:
  REGISTRY: ghcr.io

jobs:
  image:
    runs-on: ubuntu-latest
    outputs:
      tag: '${{ steps.tag.outputs.tag }}'
    steps:
      - name: Generate Image Tag
        id: tag
        run: |
          COMMIT_TIME=$(curl --fail --silent \
              --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
            | jq '(.commit.committer.date | fromdate)')
          TIMESTAMP=`date +%Y%m%d%H%M%S --date="@${COMMIT_TIME}"`
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
          IMAGE_TAG="${TIMESTAMP}-${SHORT_SHA}"
          echo $IMAGE_TAG
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  build-and-push:
    needs: image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: '${{ env.REGISTRY }}/agoric/agoric-inter-dashboard:${{ needs.image.outputs.tag }}'


            