name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Node.js 18.8.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.8.x'
      - name: Install Dependencies
        run: yarn
      - name: Run Tests
        run: yarn test
